# Generated by Django 2.2.6 on 2019-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191117_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='author',
        ),
    ]
