# Generated by Django 2.2.7 on 2019-11-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191117_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_name',
        ),
    ]
